# Generated by Django 5.1.1 on 2024-10-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
